BboardSite/urls.py
from django.contrib import admin
from django.urls import path, include
from BboardSite import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404='bboard.views.page_not_found'
handler403='bboard.views.forbidden'
handler500='bboard.views.server_error'

bboard/urls.py
from django.urls import path
from bboard.views import (index, about, add_post,
                          read_post, update_post, delete_post,
                          user_posts, user_info, search_post,
                          filter_post, upload_photos, add_to_favorites,
                          remove_from_favorites, favorites_list)

app_name = 'bboard'
urlpatterns = [
    path('search/', search_post, name='search_post'),
    path('filter/', filter_post, name='filter_post'),
    path('about/', about, name='about'),
    path('post/<slug:slug>/add_favorite/', add_to_favorites, name='add_to_favorites'),
    path('post/<slug:slug>/remove_favorite/', remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', favorites_list, name='favorites_list'),
    path('post/<int:pk>/delete/', delete_post, name='delete_post'),
    path('post/user/info/<int:user_id>/', user_info, name='user_info'),
    path('post/user/<int:user_id>/', user_posts, name='user_posts'),
    path('post/<int:pk>/edit/', update_post, name='update_post'),
    path('post/<slug:slug>/', read_post, name='read_post'),
    path('post/', add_post, name='add_post'),
    path('', index, name='index'),
    path('upload/', upload_photos, name='upload_photos'),
]

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out,
                    user_profile, change_password)

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('profile/<int:pk>/', user_profile, name='profile'),
    path('change_password/', change_password, name='change_password')
]

bboard/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from slugify import slugify


# описание модели поста
class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    rooms = models.IntegerField(verbose_name='Количество комнат')
    square = models.DecimalField(max_digits=4, decimal_places=1,verbose_name='Площадь квартиры')
    floor = models.IntegerField(verbose_name='Этаж')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость объекта')
    city = models.CharField(max_length=200,verbose_name='Адрес объекта')
    street = models.CharField(max_length=200, verbose_name='Улица')
    house = models.CharField(max_length=200, verbose_name='Номер дома')
    apartment = models.CharField(max_length=200,verbose_name='Номер квартиры')
    metro = models.CharField(max_length=200, verbose_name='Метро')
    text = models.TextField(verbose_name='Описание объекта')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='posts')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания', editable=False)
    image = models.ImageField(upload_to='posts/', null=True, blank=True, verbose_name='Изображение')
    slug = models.SlugField(max_length=200, unique=True, editable=False, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        slug_title = slugify(self.title)
        slug = f'{slug_title}-{self.pk}'
        self.slug = slug
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('bboard:read_post', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

    def __str__(self):
        return self.title


# новая модель для загрузки несколько фото
class Photo(models.Model):
    image = models.ImageField(upload_to='upload/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Photo {self.id}"

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favorites', verbose_name='Пользователь')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='favorited_by', verbose_name='Объявление')
    added_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    class Meta:
        unique_together = ('user', 'post')
        verbose_name = 'Избранное объявление'
        verbose_name_plural = 'Избранные объявления'

    def str(self):
        return f"{self.user.username} {self.post.title}"

bboard/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post
from .models import Photo


# class PostForm(forms.Form):
#     title = forms.CharField(max_length=200, label='Заголовок',
#                             widget=forms.TextInput(attrs={"class":"myfield_title"}))
#     rooms = forms.IntegerField(label='Количество комнат',
#                                widget=forms.NumberInput(attrs={"class":"myfield_rooms"}))
#     square = forms.IntegerField(label='Площадь квартиры',
#                                 widget=forms.NumberInput(attrs={"class":"myfield_square"}))
#     floor = forms.IntegerField(label='Этаж', widget=forms.NumberInput(attrs={"class":"myfield_floor"}))
#     price = forms.DecimalField(max_digits=10, decimal_places=2, label='Цена',
#                                widget=forms.NumberInput(attrs={"class":"myfield_price"}))
#     city = forms.CharField(max_length=200, label='Город',
#                            widget=forms.TextInput(attrs={"class":"myfield_city"}))
#     metro = forms.CharField(max_length=200, label='Метро',
#                             widget=forms.TextInput(attrs={"class":"myfield_metro"}))
#     street = forms.CharField(max_length=200, label='Улица',
#                              widget=forms.TextInput(attrs={"class":"myfield_street"}))
#     house = forms.CharField(max_length=200, label='Номер дома',
#                             widget=forms.NumberInput(attrs={"class":"myfield_house"}))
#     apartment = forms.CharField(max_length=200, label='Номер квартиры',
#                                 widget=forms.NumberInput(attrs={"class":"myfield_apartment"}))
#     text = forms.CharField(widget=forms.Textarea(attrs={"class": "myfield_text"}), label='Описание объекта')
#     author = forms.ModelChoiceField(queryset=User.objects.all(), label='Автор',
#                                     widget=forms.TextInput(attrs={"class":"myfield"}))
#     image = forms.ImageField(required=False, label='Изображение')

class PostForm(forms.ModelForm):
    # дополняем конструктор родительского класса
    def __init__(self, *args, **kwargs):
        # получаем author из именованных аргументов (его передали во views)
        if kwargs.get('initial'):
            author = kwargs['initial'].pop('author')
        else:
            author = kwargs.pop('author')
        # вызываем конструктор родительсого
        super().__init__(*args, **kwargs)
        # устанавливаем начальное значение поля author
        self.fields['author'].initial = author
        # отключаем видимость этого поля в форме
        self.fields['author'].disabled = True
        self.fields['author'].widget = forms.HiddenInput()

    class Meta:
        model = Post
        fields = ('title', 'rooms','square',
                  'floor', 'price','city',
                  'metro', 'street', 'house',
                  'apartment', 'text', 'image',
                  'author',
                  )

        labels = {
            'title': 'Заголовок',
            'rooms': 'Количество комнат',
            'square': 'Общая площадь квартиры',
            'floor': 'Этаж',
            'price': 'Цена',
            'city': 'Город',
            'metro': 'Метро',
            'street': 'Улица',
            'house': 'Номер дома',
            'apartment': 'Номер квартиры',
            'text': 'Описание объекта',
            'image': 'Изображение',
        }

class FilterForm(forms.Form):
    author = forms.ModelChoiceField(queryset=User.objects.all(),
                                    label='Автор',
                                    required=False)
    created_at = forms.DateField(label='Дата публикации',
                                 widget=forms.DateInput(attrs={'type': 'date'}),
                                 input_formats=['%Y-%m-%d'],
                                 required=False)

    # новая форма для загрузки несколько фото
class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True  # Разрешаем выбор нескольких файлов

class MultiplePhotoForm(forms.ModelForm):
    image = forms.FileField(
        widget=MultipleFileInput(attrs={'multiple': True}),
        label='Выберите фото',
        help_text='Можно выбрать несколько файлов'
    )

    class Meta:
        model = Photo
        fields = ['image']

bboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Post, Favorite
from .forms import PostForm, FilterForm
from .forms import MultiplePhotoForm
from .models import Photo
from django.contrib import messages


def index(request):
    # получение всех постов, отсортированных по дате публикации
    # (select * from bboard_post order by created_at DESK)
    posts = Post.objects.all().order_by('-created_at')
    count_posts = Post.objects.count()
    # показываем по три поста на странице
    per_page = 3
    paginator = Paginator(posts, per_page)
    # получаем номер страницы из URL
    page_number = request.GET.get('page')
    # получаем объекты для текущей страницы
    page_obj = paginator.get_page(page_number)
    filter_form = FilterForm
    context = {
        'title':'Главная страница',
        'page_obj': page_obj,
        'count_posts': count_posts,
        'filter_form': filter_form
    }
    return render(request, template_name='bboard/index.html', context=context)


def about(request):
    count_posts = Post.objects.count()
    context = {'title': 'О сайте', 'count_posts': count_posts}
    return render(request, template_name='bboard/about.html', context=context)

@login_required
def add_post(request):
    if request.method == 'GET':
        post_form = PostForm(author=request.user)
        context = {'title': 'Добавить объявление','form': post_form}
        return render(request, template_name='bboard/post_add.html', context=context)

    if request.method == 'POST':
        post_form = PostForm(data=request.POST, files=request.FILES, author=request.user)
        if post_form.is_valid():
            # post = Post()
            # post.title = post_form.cleaned_data['title']
            # post.rooms = post_form.cleaned_data['rooms']
            # post.square = post_form.cleaned_data['square']
            # post.floor = post_form.cleaned_data['floor']
            # post.price = post_form.cleaned_data['price']
            # post.metro = post_form.cleaned_data['metro']
            # post.city = post_form.cleaned_data['city']
            # post.street = post_form.cleaned_data['street']
            # post.house = post_form.cleaned_data['house']
            # post.apartment = post_form.cleaned_data['apartment']
            # post.text = post_form.cleaned_data['text']
            # post.author = post_form.cleaned_data['author']
            # post.image = post_form.cleaned_data['image']
            # post.save()
            post_form.save()
            return index(request)
        return None
    return None


def read_post(request, slug):
    # post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, slug=slug)
    context = {'title': 'Информация об объекте', 'post': post}
    return render(request, template_name='bboard/post_detail.html', context=context)

@login_required
def update_post(request, pk):
    # post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post_form = PostForm(data=request.POST,
                             files=request.FILES,
                             instance=post,
                             initial={'author':post.author})
        if post_form.is_valid():
            post_form.save()
            return redirect('bboard:read_post', slug=post.slug)
        return None
    else:
        post_form = PostForm(initial={
            'title': post.title,
            'rooms': post.rooms,
            'square': post.square,
            'floor': post.floor,
            'price': post.price,
            'metro': post.metro,
            'city': post.city,
            'street': post.street,
            'house': post.house,
            'apartment': post.apartment,
            'text': post.text,
            'author': post.author,
            'image': post.image,
        })
        return render(request, template_name='bboard/post_edit.html', context={'form': post_form})


def delete_post(request, pk):
    # post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    context = {'post': post}
    if request.method == 'POST':
        post.delete()
        return redirect('bboard:index')
    return render(request, template_name='bboard/post_delete.html', context=context)

def user_posts(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # posts = user.posts.all()
    posts = Post.objects.filter(author=user).select_related('author')
    context = {'user': user, 'posts': posts}
    return render(request, template_name='bboard/user_posts.html', context=context)


@login_required
def user_info(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    context = {'user': user}
    return render(request, template_name='bboard/user_info.html', context=context)

def page_not_found(request, exception):
    return render(request, template_name='bboard/404.html', context={'title': '404'})


def forbidden(request, exception):
    return render(request, template_name='bboard/403.html', context={'title': '403'})


def server_error(request):
    return render(request, template_name='bboard/500.html', context={'title': '500'})


def search_post(request):
    query = request.GET.get('query')
    query_text = Q(title__icontains=query) | Q(metro__icontains=query) | Q(street__icontains=query)
    results = Post.objects.filter(query_text)

    per_page = 3
    paginator = Paginator(results, per_page)
    # получаем номер страницы из URL
    page_number = request.GET.get('page')
    # получаем объекты для текущей страницы
    page_obj = paginator.get_page(page_number)
    count_posts = results.count()
    context = {
        'title': 'Главная страница',
        'page_obj': page_obj,
        'count_posts': count_posts
    }
    return render(request, template_name='bboard/index.html', context=context)

def filter_post(request):
    author_id = request.GET.get('author')
    if not author_id:
        results = Post.objects.all()
    else:
        author = User.objects.get(pk=author_id)
        query_text = Q(author__exact=author)
        results = Post.objects.filter(query_text)

    per_page = 3
    paginator = Paginator(results, per_page)
    # получаем номер страницы из URL
    page_number = request.GET.get('page')
    # получаем объекты для текущей страницы
    page_obj = paginator.get_page(page_number)
    count_posts = results.count()
    filter_form = FilterForm
    context = {
        'title': 'Главная страница',
        'page_obj': page_obj,
        'count_posts': count_posts,
        'filter_form': filter_form
    }
    return render(request, template_name='bboard/index.html', context=context)

 # новое представление для загрузки несколько фото
def upload_photos(request):
    if request.method == 'POST':
        form = MultiplePhotoForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('image')  # Получаем список файлов
            for file in files:
                Photo.objects.create(images=file)  # Создаем запись для каждого файла
            return redirect('bboard/index.html')  # Замените на ваш URL
    else:
        form = MultiplePhotoForm()

        # MAX_FILES = 5
        # if len('files') > MAX_FILES:
        #     form.add_error('image', f'Максимум {MAX_FILES} файлов.')

    return render(request, 'bboard/upload.html', {'form': form})


@login_required
def favorites_list(request):
    favorites = Favorite.objects.filter(user=request.user).select_related('post')
    context = {'favorites': favorites, 'title': 'Мои избранные посты'}
    return render(request, 'bboard/favorites_list.html', context)

@login_required
def add_to_favorites(request, slug):
    post = get_object_or_404(Post, slug=slug)
    Favorite.objects.get_or_create(user=request.user, post=post)
    return redirect('bboard:read_post', slug=slug)

@login_required
def remove_from_favorites(request, slug):
    post = get_object_or_404(Post, slug=slug)
    Favorite.objects.filter(user=request.user, post=post).delete()
    return redirect('bboard:read_post', slug=slug)

bboard/templates/bboard/about.html
{% extends 'bboard/base.html' %}

{% block content %}

<div class="bboard">
    <h1>О сайте</h1>
</div>

<div class="bboard_text" style="padding:30px; text-align: justify;">
    <h4>Добро пожаловать на сайт <span><b>Каталог квартир</b></span>— ваш надежный помощник в покупке и продаже квартир на вторичном рынке!</h4>
    <h4>Мы специализируемся на подборе недвижимости, проверке юридической чистоты сделок и
        профессиональном сопровождении клиентов на всех этапах.
        Наша цель — сделать процесс покупки или продажи квартиры максимально простым,
        безопасным и выгодным.</h4>
</div>

<div class="blog" style="padding-left: 30px;">
    <p><h4>
        На сайте <span><b>{{ count_posts }}</b> объявлений.</span>
    </h4></p>
</div>
{% endblock content %}

bboard/templates/bboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{{title}}</title>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="header">
    <nav class="nav">
        <a class="text-white text-decoration-none" style="font-weight: bold; "
           aria-current="page" href="{% url 'bboard:index' %}">Главная</a>
        <a class="text-white text-decoration-none" href="{% url 'bboard:add_post' %}">Добавить объявление</a>
        <a class="text-white text-decoration-none" href="{% url 'bboard:favorites_list' %}">Избранное</a>
        <a class="text-white text-decoration-none" href="{% url 'bboard:about' %}">О сайте</a>
        {% if not user.is_authenticated %}
        <a class="text-white text-decoration-none" href="{% url 'users:register' %}">Регистрация</a>
        <a class="text-white text-decoration-none" href="{% url 'users:login' %}">Войти</a>
        {% else %}
        <a class="nav-link"  href="{% url 'users:profile' pk=user.pk %}">{{user.username }}</a>
        <a class="nav-link"  href="{% url 'users:logout' %}">Выйти</a>
        {% endif %}
    </nav>
</div>


{% if messages %}
{% for message in messages %}
<div>{{ message }}</div>

{% endfor %}
{% endif %}

{% block content %}
{% endblock content %}
</body>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</html>

bboard/templates/bboard/index.html
{% extends 'bboard/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
<div class="bboard-main"
     style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
    <h1>Каталог квартир</h1>
    <div class="search-btn">
        <form action="{% url 'bboard:search_post' %}" method="get" style="display: flex; gap: 10px;">
            <input type="search" name="query" placeholder="Поиск..."
                   style="padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
            <button type="submit"
                    style="padding: 8px 16px; background-color: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer;">
                Поиск
            </button>
        </form>
    </div>
</div>




{% if page_obj|length == 0 %}
<h2>По вашему запросу не найдено ни одного поста!</h2>
{% else %}
<div class="post-list" style="margin: 20px">
    <!-- Список объявлений -->
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
        {% for post in page_obj %}
        <div class="col">
            <div class="card h-100 shadow-sm">
                <!-- Изображение -->
                <div class="post-image" style="height: 200px; overflow: hidden;">
                    {% if post.image %}
                    <img src="{{ post.image.url }}" class="card-img-top h-100 w-100" style="object-fit: cover;"
                         alt="{{ post.title }}">
                    {% else %}
                    <img src="{% static 'img/no_image.png' %}" class="card-img-top h-100 w-100"
                         style="object-fit: cover;" alt="Нет изображения">
                    {% endif %}
                </div>

                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{ post.get_absolute_url }}" class="text-decoration-none">{{ post.title }}</a>
                    </h5>

                    <div class="card-text">
                        <p class="mb-1">
                            <i class="bi bi-door-open"></i>
                            {{ post.rooms }}-комнатная, {{ post.square }} м²
                        </p>
                        <p class="mb-1">
                            <i class="bi bi-building"></i>
                            {{ post.floor }} этаж
                        </p>
                        <p class="mb-1 text-success fw-bold">
                            <i class="bi bi-currency-ruble"></i>
                            {{ post.price }}
                        </p>
                        <p class="mb-1">
                            <i class="bi bi-geo-alt"></i>
                            {{ post.city }}, ул. {{ post.street }}, д. {{ post.house }}
                        </p>
                        <p class="mb-1">
                            <i class="bi bi-subway"></i>
                            Метро: {{ post.metro }}
                        </p>
                    </div>
                </div>

                <div class="card-footer bg-white">
                    <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">
                            <a href="{% url 'bboard:user_posts' user_id=post.author.pk %}" class="text-decoration-none">
                                <i class="bi bi-person"></i> {{ post.author }}
                            </a>
                        </small>
                        <small class="text-muted">
                            <i class="bi bi-clock"></i> {{ post.created_at|date:"d.m.Y" }}
                        </small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number == num %}active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
        {% endif %}
    </ul>
</nav>

<div class="footer">
    <p>&copy; 2025 Сайт объявлений.
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill"
             viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                  d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
        </svg>
        +7(911)707-52-15
    </p>
</div>

{% endblock content %}

bboard/templates/bboard/post_add.html
{% extends 'bboard/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm mt-5">
                <div class="card-body p-4">
                    <h2 class="text-center mb-4" style="text-shadow: -5px -4px 3px #999;">Добавить объявление</h2>

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary w-100">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bboard/templates/bboard/post_detail.html
{% extends 'bboard/base.html' %}
{% load static %}

{% block content %}

<div class="bboard">
    <h2>Информация об объекте № {{ post.pk }}</h2>
</div>

<!--# отобразить информацию о посте, добавить детализацию по объявлению-->
<div class="rooms" style="margin-bottom: 15px; margin-top: 15px; padding-left: 30px;">
    <h4><b>{{ post.title }}</b></h4>
</div>

<div class="price" style="padding-left: 30px;">
    <p><h5>Цена <b>{{ post.price }} руб.</b></h5></p>
</div>

<div class="post-container">
    <div class="image" style="padding-left: 30px;">
        {% if post.image %}
        <img src="{{ post.image.url }}" width="400px" height="auto">
        {% else %}
        <img src="{% static 'img/no_image.png' %}" width="400px" height="auto">
        {% endif %}
    </div>

    <div class="adress" style="padding-left: 30px;">
        <a>Адрес: <b>{{ post.city }}, ул. {{ post.street }}, дом {{ post.house }}, кв. {{ post.apartment }}</b></a>
        <p>Метро: <b>{{ post.metro }}</b></p>
        <p>{{ post.rooms }}-комн.квартира, {{ post.square }} м² на {{ post.floor }} этаже</p>

        <div class="text">
            <p>{{ post.text }}</p>
        </div>

        <div class="btn-favorites">
            {% if user.is_authenticated %}
            {% if post.id in user_favorites %}
            <a href="{% url 'bboard:remove_from_favorites' post.slug %}">
                <button type="button" style="padding: 8px 16px; background-color: #007bff; color: white;
                                border: none; border-radius: 4px; cursor: pointer;">Удалить из избранного</button>
            </a>
            {% else %}
            <a href="{% url 'bboard:add_to_favorites' post.slug %}">
                <button type="button" style="padding: 8px 16px; background-color: #007bff; color: white;
                                border: none; border-radius: 4px; cursor: pointer;">Добавить в избранное ❤️</button>
            </a>
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>


<div class="aythor" style="padding-left: 30px;">
    {% if user.is_authenticated %}
    <a href="{% url 'bboard:user_info' user_id=post.author.pk %}">
        <i>{{ post.author }}</i>
    </a>
    {% else %}
    <i>{{ post.author }}</i>
    {% endif %}

    <p><i>{{ post.created_at }}</i></p>
</div>

<div class="btn-actions" style="padding-left: 30px; display: flex">
    {% if user == post.author %}
    <div class="btn-edit-post">
        <a href="{% url 'bboard:update_post' pk=post.id %}">
            <button type="button" style="margin-left: 50px; margin-bottom: 20px; padding: 8px 16px; background-color: #007bff; color: white;
                                border: none; border-radius: 4px; cursor: pointer; ">Редактировать</button>
        </a>
    </div>
    <div class="btn-del-post">
        <a href="{% url 'bboard:delete_post' pk=post.id %}">
            <button type="button" style="margin-left: 30px; padding: 8px 16px;
                                   background-color: rgb(245, 54, 54); color: white; border: none;
                                   border-radius: 4px; cursor: pointer;">Удалить</button>
        </a>
    </div>
</div>
{% else %}

{% if user.is_superuser %}
<div class="btn-actions">
    <div class="btn-del-post">
        <a href="{% url 'bboard:delete_post' pk=post.id %}">
            <button type="button">Удалить</button>
        </a>
    </div>
</div>
{% endif %}
{% endif %}

{% endblock content %}

bboard/templates/bboard/upload.html
{% extends 'bboard/base.html' %}

{% block content %}

<div class="bboard">
    <h2>Загрузить фото</h2>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Загрузить</button>
</form>

{% endblock content %}