BboardSite/urls.py
from django.contrib import admin
from django.urls import path, include
from BboardSite import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404='bboard.views.page_not_found'
handler403='bboard.views.forbidden'
handler500='bboard.views.server_error'

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out,
                    user_profile, change_password)

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('profile/<int:pk>/', user_profile, name='profile'),
    path('change_password/', change_password, name='change_password')
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.contrib.auth.forms import SetPasswordForm
from django.core.exceptions import ValidationError


class RegistrationForm(UserCreationForm):
    username = forms.CharField(label='Логин',
                               error_messages={
                                   'required': 'Пожалуйста, введите логин'
                               },
                               widget=forms.TextInput(attrs={"class":"myfield"}))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={"class":"myfield"}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={"class":"myfield"}))
    email = forms.EmailField(label='Электронная почта', widget=forms.TextInput(attrs={"class":"myfield"}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={"class":"myfield"}))
    password2 = forms.CharField(label='Подтвердите пароль',
                                widget=forms.PasswordInput(attrs={"class":"myfield"}),
                                error_messages={
                                    'required': 'Пожалуйста, подтвердите пароль'
                                })

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')

class NewRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
                               error_messages={
                                   'required': 'Пожалуйста, введите логин'
                               },
                               widget=forms.TextInput(attrs={"class": "myfield"}))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={"class": "myfield"}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={"class": "myfield"}))
    email = forms.EmailField(label='Электронная почта', widget=forms.TextInput(attrs={"class": "myfield"}))
    password = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={"class": "myfield"}))
    password2 = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput(attrs={"class":"myfield"}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password')
        help_texts = {
            'username': ''
        }
    def clean_password2(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['password'] != cleaned_data['password2']:
            raise forms.ValidationError('Пароли не совпадают!')
        return cleaned_data['password2']


class CustomPasswordChangeForm(SetPasswordForm):
    old_password = forms.CharField(
        label='Старый пароль',
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomlete': 'current-password', 'autofocus': True, 'class': 'myfield_old_password'}
        ),
    )
    new_password1 = forms.CharField(
        label='Новый пароль',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'myfield_new_password1'})
    )
    new_password2 = forms.CharField(
        label='Подтвердите пароль',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'myfield_new_password2'})
    )
    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get('old_password')
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if old_password and new_password1:
            if old_password == new_password1:
                raise ValidationError('Новый пароль должен отличаться от старого')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise ValidationError('Введенные пароли не совпадают')

        return cleaned_data

users/views.py
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages

from .forms import RegistrationForm, NewRegistrationForm, CustomPasswordChangeForm
from BboardSite.settings import LOGIN_REDIRECT_URL


def register(request):
    # когда отправляем заполненную форму на сервер
    if request.method == 'POST':
        # создаем объект формы с данными из запроса
        form = NewRegistrationForm(request.POST)
        # если форма валидна
        if form.is_valid():
            # создаем объект пользователя без записи в БД
            new_user = form.save(commit=False)
            # хэшируем пароль при помощи set_password
            new_user.set_password(form.cleaned_data['password'])
            # сохраняем пользователя в БД
            new_user.save()
            context = {'title': 'Регистрация завершена', 'new_user': new_user}
            return render(request, template_name='users/registration_done.html', context=context)

    # если метод GET (страница с пустой формой регистрации)
    form = NewRegistrationForm()
    context = {'title': 'Регистрация пользователя', 'register_form': form}
    return render(request, template_name='users/registration.html', context=context)


def log_in(request):
    # создание формы аутенфикации
    form = AuthenticationForm(request, request.POST)
    #проверка формы
    if form.is_valid():
        # полученик логина и пароля из формы
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        # аутентификация пользователя
        # проверка существования пользователя и корректности пароля
        user = authenticate(username=username, password=password)
        if user:
            #авторизация пользователя
            login(request, user)
            # получение дальнейшего маршрута после входа на сайт
            # next - путь, откуда пришел пользователь на страницу входа
            url = request.GET.get('next', LOGIN_REDIRECT_URL)
            return redirect(url)
    context = {'form': form}
    return render(request, template_name='users/login.html', context=context)

@login_required
def log_out(request):
    logout(request)
    return redirect('bboard:index')

@login_required
def user_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        raise PermissionDenied()
    context = {'user': user, 'title': 'Информация о пользователе'}
    return render(request, template_name='users/profile.html', context=context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            if not request.user.check_password(old_password):
                messages.error(request, 'Старый пароль не верный')
            else:
                user = form.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Ваш пароль успешно изменен')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибку')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, template_name='users/change_password.html', context={'form': form})

# def change_password(request):
#     if request.method == "POST":
#         form = CustomPasswordChangeForm(request.user, request.POST)
#         if form.is_valid():
#             old_password = form.cleaned_data['old_password']
#             if not request.user.check_password(old_password):
#                 messages.error(request, 'Старый пароль не верный')
#             else:
#                 user = form.save()
#                 update_session_auth_hash(request, user)
#                 messages.success(request, 'Ваш пароль успешно изменен')
#         else:
#             messages.error(request, 'Пожалуйста, исправьте ошибки')
#     else:
#         form = CustomPasswordChangeForm(request.user)
#     return render(request, template_name='users/change_password.html', context={'form': form})

users/templates/users/change_password.html
{% extends 'bboard/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card shadow-sm mt-5">
                <div class="card-body p-4">
                    <h2 class="text-center mb-4">Смена пароля</h2>

                    <div class="registration">

                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary w-100">Зарегистрироваться</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

users/templates/users/login.html
{% extends 'bboard/base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-sm mt-5">
                <div class="card-body p-4">
                    <h2 class="text-center mb-4">Пожалуйста, войдите на сайт</h2>

                    <form method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" id="id_username" name="username" required>
                        </div>

                        <div class="mb-4">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" id="id_password" name="password" required>
                        </div>

                        <button type="submit" class="btn btn-primary w-100 mb-3">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'bboard/base.html' %}

{% block content %}

<div class="bboard">
    <h3>Информация о пользователе</h3>
</div>

<div class="profile" style="padding-left: 30px;">
    <div>Логин - {{ user.username }}</div>
    <div>Имя - {{ user.first_name }}</div>
    <div>Фамилия - {{ user.last_name }}</div>
    <div>Электронная почта - {{ user.email }}</div>
    <div>Дата регистрации: {{ user.date_joined }}</div>
    <a href="{% url 'users:change_password' %}">
        <button type="button" style="padding: 8px 16px; background-color: #007bff; color: white;
                                border: none; border-radius: 4px; cursor: pointer;">Сменить пароль</button>
    </a>
</div>


{% endblock content %}

users/templates/users/registration.html
{% extends 'bboard/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card shadow-sm mt-5">
                <div class="card-body p-4">
                    <h2 class="text-center mb-4">Регистрация пользователя</h2>

                    <div class="registration">

                        <form method="post">
                            {% csrf_token %}
                            {{ register_form }}
                            {% if register_form.username.errors %}
                            {% for error in register_form.username.errors %}
                            <b>{{ error }}</b>
                            {% endfor %}
                            {% endif %}
                            <button type="submit" class="btn btn-primary w-100">Зарегистрироваться</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration_done.html
{% extends 'bboard/base.html' %}

{% block content %}

<div class="registration-done" style="padding-left: 30px;">
    <h3>Добро пожаловать, {{new_user}}!</h3>
</div>

{% endblock content %}